checkpoints_dir: /scratche/users/sansiddh/LIDC-IDRI/checkpoints
seed: 0
cudnn_deterministic : True
cudnn_benchmark : False
disable_debug_apis: True

task_type: semantic-segmentation

model: 
    name: Unet
    params:
        encoder_name: resnet50
        encoder_weights: imagenet
        in_channels: 3
        classes: 1

data:
    dataset: LIDC-IDRI
    dataset_params:
        split_version: null
        sample : null
        fraction: 1
    # For googlenet and inception use [300, 300], else [224, 224]
    imgsize: [224, 224]
    dataloader_params:
        batch_size : 64
        shuffle: True
        num_workers: 10
        pin_memory: True
    augmentations:
        # Refer to dataaugs.yml for an exhaustive list of augmentations and their paramters.
        augs:
            HorizontalFlip: 
                p: 0.5
            CropAndPad:
                percent: [-0.3, 0.3]
                p: 0.8
            RandomResizedCrop: 
                height: 224
                width: 224
                p: 0.5
            GaussianBlur:
                p: 0.5
            GaussNoise:
                p: 0.5
            ElasticTransform:
                p: 0.2
            Rotate:
                p: 0.5
        normalization:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
        bbox_aug: False
        bbox_aug_params:
            format: coco
            min_area: 1024
            min_visibility: 0.1
            label_fields: [class_labels] 

train:
    loss: DiceLoss
    loss_params:
        mode : binary
        # classes: 1
    optimizer: Adam
    optimizer_params:
        lr : 1.0e-4
        # weight_decay : 1.0e-4
        # momentum: 0.9
    lr_scheduler: StepLR
    lr_scheduler_params:
        step_size: 5
        gamma: 0.5
        verbose: True
    use_amp: True
    num_epochs : 50
    resume_checkpoint: 1

inference:
    loss: DiceLoss
    loss_params:
        mode : binary
    use_amp: True

wandb:
    name: null
    project: lung-ct
    entity: sansiddhjain

eval:
    logging_metrics:
        label_metrics: [accuracy_score, confusion_matrix, f1_score,
                        precision_score, recall_score]
        score_metrics: [roc_auc_score, average_precision_score]
        mask_metrics: [accuracy_score, confusion_matrix, f1_score,
                       precision_score, recall_score]
    ckpt_metric: roc_auc_score